# Generated by Django 4.2.4 on 2023-09-17 11:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=44, verbose_name='name (English)')),
                ('name_ar', models.CharField(max_length=44, verbose_name='name (Arabic)')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=33, verbose_name='title (Arabic)')),
                ('location_ar', models.CharField(max_length=80, verbose_name='location (Arabic)')),
                ('description_ar', ckeditor.fields.RichTextField(verbose_name='description (Arabic)')),
                ('title_en', models.CharField(max_length=33, verbose_name='title (English)')),
                ('location_en', models.CharField(max_length=80, verbose_name='location (English)')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='description (English)')),
                ('job_type', models.CharField(choices=[('Partly time', 'Partly time'), ('Fully time', 'Fully time')], max_length=40, verbose_name='job type')),
                ('vacancy', models.IntegerField(default=1, verbose_name='vacancy')),
                ('salary', models.IntegerField(default=0, verbose_name='salary')),
                ('experience', models.IntegerField(default=1, verbose_name='experience')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d', verbose_name='image')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='published at')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myjob.category', verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=88, verbose_name='email')),
                ('website', models.URLField(verbose_name='website')),
                ('cv', models.FileField(upload_to='apply/', verbose_name='cv')),
                ('cover_letter', models.TextField(verbose_name='cover letter')),
                ('Applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applier', to=settings.AUTH_USER_MODEL, verbose_name='Applier')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='myjob.job', verbose_name='job')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myjob.job')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='myjob_comme_created_e28fe5_idx')],
            },
        ),
    ]
