# Generated by Django 4.2.4 on 2023-09-17 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myjob', '0002_rename_post_comment_job'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='myjob_comme_created_e28fe5_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='myjob_comme_created_6dbbda_idx'),
        ),
    ]
