# Generated by Django 4.2.4 on 2023-09-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0003_remove_comment_myjob_comme_created_e28fe5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
