# Generated by Django 4.2.4 on 2023-09-21 19:48

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('myjob', '0004_remove_comment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='myjob_comme_created_6dbbda_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to='apply/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Please upload a PDF file.')], verbose_name='cv'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='myjob_comme_created_e28fe5_idx'),
        ),
    ]
