# Generated by Django 4.2.4 on 2023-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0005_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
    ]
