# Generated by Django 4.2.4 on 2023-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0007_job_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique_for_date='publish', verbose_name='slug'),
        ),
    ]
