# Generated by Django 4.2.4 on 2023-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0008_alter_job_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Job_tags',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
