# Generated by Django 4.2.4 on 2023-09-25 07:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('myjob', '0009_rename_job_tags_job_tags_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
