# Generated by Django 4.2.4 on 2023-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0002_category_myjob_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='vailable',
            field=models.BooleanField(default=True),
        ),
    ]
