# Generated by Django 4.2.4 on 2023-08-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0003_myjob_vailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='location',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
