# Generated by Django 4.2.4 on 2023-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0004_myjob_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d'),
        ),
    ]
