# Generated by Django 4.2.4 on 2023-08-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0005_myjob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='sulg',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
