# Generated by Django 4.2.4 on 2023-08-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0006_myjob_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myjob',
            old_name='sulg',
            new_name='slug',
        ),
    ]
