# Generated by Django 4.2.4 on 2023-08-14 21:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0007_rename_sulg_myjob_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjob',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
