# Generated by Django 4.2.4 on 2023-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0012_remove_apply_name_apply_applier'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
