# Generated by Django 4.2.4 on 2023-08-29 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myjob', '0013_myjob_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myjob',
            name='onwer',
        ),
        migrations.AddField(
            model_name='myjob',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='Applier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applier', to=settings.AUTH_USER_MODEL),
        ),
    ]
