# Generated by Django 4.2.4 on 2023-08-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0014_remove_myjob_onwer_myjob_owner_alter_apply_applier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myjob',
            name='approved',
        ),
    ]
