# Generated by Django 4.2.4 on 2023-08-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0015_remove_myjob_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myjob',
            old_name='vailable',
            new_name='available',
        ),
    ]
