# Generated by Django 4.2.4 on 2023-09-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0016_rename_vailable_myjob_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
