# Generated by Django 4.2.4 on 2023-09-07 18:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cover_letter',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
