# Generated by Django 4.2.4 on 2023-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0019_student_alter_apply_applier_alter_apply_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myjob',
            name='description',
        ),
        migrations.RemoveField(
            model_name='myjob',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='myjob',
            name='location',
        ),
        migrations.RemoveField(
            model_name='myjob',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default=1, max_length=44, verbose_name='name (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=1, max_length=44, verbose_name='name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='description_ar',
            field=models.TextField(default=1, verbose_name='description (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='description_en',
            field=models.TextField(default=1, verbose_name='description (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='job_type_ar',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default=1, max_length=40, verbose_name='job type (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='job_type_en',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default=1, max_length=40, verbose_name='job type (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='location_ar',
            field=models.CharField(default=1, max_length=80, verbose_name='location (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='location_en',
            field=models.CharField(default=1, max_length=80, verbose_name='location (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='title_ar',
            field=models.CharField(default=1, max_length=33, verbose_name='title (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myjob',
            name='title_en',
            field=models.CharField(default=1, max_length=33, verbose_name='title (English)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(verbose_name='cover letter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='myjob',
            name='published_at',
            field=models.DateTimeField(auto_now=True, verbose_name='published at'),
        ),
    ]
