# Generated by Django 4.2.4 on 2023-09-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0020_remove_category_name_remove_myjob_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
