# Generated by Django 4.2.4 on 2023-09-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0024_alter_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type_ar',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type_en',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default=1, max_length=40, verbose_name='job type'),
            preserve_default=False,
        ),
    ]
