# Generated by Django 4.2.4 on 2023-09-17 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myjob', '0027_alter_comment_options_remove_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Applier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applier', to=settings.AUTH_USER_MODEL, verbose_name='Applier'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='myjob.job', verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myjob.job'),
        ),
    ]
