# Generated by Django 4.2.4 on 2023-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
    ]
